# Generated by Django 2.2.4 on 2020-12-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dojo',
            new_name='DojoSai',
        ),
    ]
