# Generated by Django 2.2.4 on 2020-12-15 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0004_auto_20201215_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='Dojos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ninja', to='dojo_app.DojoSai'),
        ),
    ]
