# Generated by Django 2.2.4 on 2020-12-15 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0005_ninja_dojos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='Dojos',
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojo_app.DojoSai'),
        ),
    ]
