# Generated by Django 2.2.4 on 2021-01-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=255)),
                ('last', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('likes', models.ManyToManyField(related_name='liked_Post', to='wall_app.User')),
                ('usersPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_post', to='wall_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('likes', models.ManyToManyField(related_name='likedComment', to='wall_app.User')),
                ('postComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_comment', to='wall_app.Post')),
                ('usersComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_comment', to='wall_app.User')),
            ],
        ),
    ]
